site_name: Wifaqul Ulama API
theme:
  name: material
  icon:
    repo: fontawesome/brands/git-alt
  palette:
    - media: "(prefers-color-scheme: light)" #
      scheme: default
      primary: white
      accent: blue
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)" #
      scheme: slate
      primary: blue
      accent:  blue
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode
  logo: assets/ic_logo.svg
  favicon: assets/logo.png
  features:
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.expand
    - toc.integrate
    - navigation.top
extra:
  generator: false
  social:
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/WifaqulUlama
    - icon: fontawesome/brands/facebook
      link: https://www.facebook.com/wifaqululama/
    - icon: fontawesome/brands/instagram
      link: https://www.instagram.com/wifaqululama/
    - icon: fontawesome/brands/youtube
      link: https://www.youtube.com/channel/UCp09rxJNlTeLyhri_qcpakQ
    - icon: fontawesome/brands/github
      link: https://github.com/wifaqululama
copyright: Copyright &copy; 2021 - Wifaqul Ulama
repo_url: https://github.com/wifaqululama/api_v2
repo_name: GitHub repository
nav:
  - Date:
    - Hijri Date API: date/index.md
    - Supported Countries: date/supported-countries.md
    - Milestones: date/milestones.md
    - Legacy API Compatibility Layer: date/legacy.md
  - Salah Times: times/index.md
  - Financial Numbers: finanical-numbers/index.md
  - Other:
      - Qibla: other/qibla.md
markdown_extensions:
  - pymdownx.highlight
  - pymdownx.inlinehilite
  - pymdownx.superfences
  - pymdownx.snippets
  - tables
